### ISSUE TITLE
Can't resolve 'liowebrtc'

### ISSUE THREAD

**Issue by Phobia1971** [lazorfuzz/react-liowebrtc#7]
I'm using ubuntu 18.04, node v8.16.1 and npm 6.4.1

I cloned the repo.
But after npm start i get  Can't resolve 'liowebrtc'

I checked in the node_modules folder and i can confirm "/react-liowebrtc/dist/index.es.js" is there and index.js

I gave all files chmod 777

But it will not start

to be save i also tried yarn run start, but ti's also din't work
![Screenshot from 2019-08-25 02-16-44](https://user-images.githubusercontent.com/5323899/63644004-720ced80-c6de-11e9-952a-f146ef1b0191.png)

**Comment by lazorfuzz** [comment]
@Phobia1971 Thanks, just fixed it, and published it to npm. Updating your react-liowebrtc to the latest version should work.

**Comment by saint13th** [comment]
Hello, not works with CRA
Module not found: Can't resolve 'react-liowebrtc'
